name: My First workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 
      - name: Welcome messages
        run: echo "My first GitHub Action Job"

      - name: List file
        run: cat README.md
