name: Generate ASCII Artwork

on: 
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Executing shell script
        run: ls -ltra

 
 
      - name: Execute shell CMD
        run: ./github/workflows/ascii-script.sh